### ISSUE TITLE
dplyr function errors

### ISSUE THREAD

**Issue by ShashiDhungel** [bnosac/spark.sas7bdat#4]
When you upload a file using spark_read_sas and then create an R object using part of the data then it often throws and error.

Create a connection using sparklyr in R studio.
sc<-spark_connect(master = "local", config = config)

read a file using spark_read_sas

mydata<-spark_read_sas(sc, "/your path/ .sas7bdat", Alldata)

create an R object using dplyr

mydata_1 <- mydata %>% select(A,B,C,D)

Now apply a function 

mydata_1 %>% summarise_all(function(x) sum(is.na(x)))

It throws the following error

Error in as.character(x[[1]]) : 
  cannot coerce type 'closure' to vector of type 'character'

Note: If you run the same code using haven library's read_sas it works fine.

**Comment by jwijffels** [comment]
I believe you should send the request to the authors of dplyr / sparklyr or the authors of the spark-sas7bdat Spark package  https://github.com/saurfang/spark-sas7bdat
This package is merely a wrapper around this, so if you get an error using the dplyr functionalities, this most likely happens at these packages.
Please also provide them a reproducible example so that they can test it out.

**Comment by jwijffels** [comment]
Closing as no active feedback given in last month.
